---
- name: terra - crontab
  hosts: terra
  tasks:
  # Sync files between folders
    - name: "CRON: Sync reddit downloads to crypt"
      cron:
        name: "Sync reddit downloads to crypt"
        minute: "15"
        hour: "0,12"
        job: "/usr/bin/rsync -a /home/luke/bulk-downloader-for-reddit/downloads/ /mnt/virt/gdrive/crypt/reddit-saved"
        disabled: "yes"
      tags:
      - cronjobs

  # Download reddit saved posts
    - name: "CRON: Download all saved Reddit posts (u/TBA)"
      cron:
        name: "Download all saved Reddit posts (u/TBA)"
        minute: "0"
        hour: "1"
        job: "/usr/bin/docker-compose -f /home/luke/bulk-downloader-for-reddit/docker-compose.yml run --rm -p 0.0.0.0:8070:8080 -p 0.0.0.0:7634:7634 bdfr --saved --quit"
        disabled: "no"
      tags:
      - cronjobs

    # Generate & backup tree
    - name: "CRON: Generate & backup tree at 12am/pm"
      cron:
        name: "Generate & backup tree"
        minute: "0"
        hour: "0,12"
        job: '/usr/bin/tree --dirsfirst -Fn --du -Juh -I "MumDrive" -I "MumMasters" -o "/mnt/virt/gdrive/crypt/backups/trees/virt/tree-$(date +%F-%H-%MT%z).json" -- /mnt/virt'
        user: root
        disabled: "yes"
      tags:
      - cronjobs
      become: yes
