- name: Run stack deploy script
  loop: "{{ output.results | selectattr('changed', 'equalto', true) | map(attribute='item') | list }}"
  ansible.builtin.command: 'sh deploy.sh'
  args:
    chdir: "{{ DOCKER_HOME }}/compose/{{ item.path | dirname }}"
