version: '3.4'
services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
    volumes:
      - /etc/localtime:/etc/localtime:ro

      - /opt/gocrypt/media:/data

      - "${DOCKERHOME}/volumes/stash-stack/config:/root/.stash"
      - "${DOCKERHOME}/volumes/stash-stack/metadata:/metadata"
      - "${DOCKERHOME}/volumes/stash-stack/cache:/cache"
      - "${DOCKERHOME}/volumes/stash-stack/generated:/generated"
      - "${DOCKERHOME}/volumes/stash-stack/scrapers:/data/scrapers"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stash.rule=Host(`stash.${REVERSE_HOST}`)"
      - "traefik.http.routers.stash.entrypoints=web-secure"
      - "traefik.http.routers.stash.tls=true"
    networks:
      - reverse

networks:
  reverse:
    name: reverse
    external: true
