---
- name: 501 - fstab
  hosts: compute-1
  become: true
  tasks:
    - name: Mount media SMB share
      ansible.posix.mount:
        src: //omv.sol.browningluke.dev/media
        path: /mnt/media
        fstype: cifs
        opts: credentials=/root/.smbcreds,uid=1000,gid=1000,iocharset=utf8
        state: present

    - name: Mount gocryptfs SMB share
      ansible.posix.mount:
        src: //omv.sol.browningluke.dev/gocrypt
        path: /mnt/gocrypt
        fstype: cifs
        opts: credentials=/root/.smbcreds,uid=1000,gid=1000,iocharset=utf8
        state: present
