---
- name: 501 - crontab
  hosts: compute-1
  tasks:
    - name: "CRON: Mangathr(v2): Check for updates"
      ansible.builtin.cron:
        name: "Mangathr(v2): Check for updates"
        minute: "0"
        job: "/bin/sh -c 'cd {{ DOCKER_HOME }}/compose/mangathr && /usr/bin/docker compose run --rm mangathrv2'"
        user: root
        disabled: "no"
      become: true

    - name: "CRON: Mangathr(v1): Check for updates"
      ansible.builtin.cron:
        name: "Mangathr(v1): Check for updates"
        minute: "10"
        job: "/bin/sh -c 'cd {{ DOCKER_HOME }}/compose/mangathr && /usr/bin/docker compose run --rm mangathr'"
        user: root
        disabled: "no"
      become: true
