---
- name: Install Packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - ntp
    - python3
    - python3-pip
    - tcpdump
    - wget
    - openssl
    - curl

- name: Install Docker pip Packages
  ansible.builtin.pip:
    name: docker
