version: '2'

services:
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=
      - TZ=America/Nassau
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=
    volumes:
      - ./mariadb-config:/config
    ports:
      - 3306:3306
    restart: unless-stopped
  nextcloud:
    image: nextcloud
    ports:
      - 6969:80
    links:
      - mariadb
    volumes:
      - ./nextcloud:/var/www/html
    restart: always

