---
- name: Add nodes
  community.docker.docker_swarm:
    state: join
    advertise_addr: "{{ ansible_host }}"
    join_token: "{{ hostvars[groups[root_manager][0]]['swarm_root']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: ["{{ hostvars[groups[root_manager][0]]['inventory_hostname'] }}:2377"]
