---
- name: omv - crontab
  hosts: omv
  tasks:
  # Sync to GDrive
    - name: "CRON: Sync crypt to GDrive"
      cron:
        name: "Sync crypt to GDrive"
        minute: "0"
        hour: "2"
        job: '/usr/bin/rclone sync /srv/mergerfs/virt/gdrive/crypt gdrive-root-crypt: --copy-links --retries 5 --retries-sleep 30s -P --bwlimit "07:00,244k 02:00,off"'
        user: root
        disabled: "no"
      tags:
      - cronjobs
      become: yes
    
    - name: "CRON: Sync backups to GDrive"
      cron:
        name: "Sync backups to GDrive"
        minute: "30"
        hour: "3"
        job: '/usr/bin/rclone sync /srv/mergerfs/virt/gdrive/backups gdrive-root:/root/backups --copy-links --retries 5 --retries-sleep 30s -P --bwlimit "07:00,244k 02:00,off"'
        user: root
        disabled: "no"
      tags:
      - cronjobs
      become: yes
