version: "3.7"
services:
  caddy:
    build: .
    image: caddy:auth-portal
    container_name: caddy
    hostname: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN
      - CERTPATH
      - KEYPATH
      - TLSEMAIL
      - TOKEN_SECRET
      - TOKEN_ISSUER
      - GITHUB_ID
      - GITHUB_SECRET
      - UBUNTUVM_IP
      - PI4_IP
      - PI3_IP
      - MASTER_PC
    volumes:
      - ./data:/etc/caddy/