version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp"
      - "8182:80/tcp"
      - "8183:443/tcp"
    environment:
      TZ: 'America/Nassau'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
    #  - NET_ADMIN
    restart: unless-stopped
    environment:
      - ServerIP=10.8.0.109
      - PROXY_LOCATION=pihole
      - VIRTUAL_HOST=pihole0.tba.lan
      - VIRTUAL_PORT=80
      - TZ=America/Nassau
      - WEBPASSWORD=R0cb5BUEMnRw
      - DNS1=127.0.0.1
      - DNS2=8.8.8.8
